version: '3.3'

services:
    backend:
        build: server
        ports:
            - '3030:3030'
        user: ${DOCKER_UID}:${DOCKER_GID}
        volumes:
            - './data:/data'
            - './data/db:/db/db'

    frontend:
        build: website
        ports:
            - '8080:8080'
        environment:
            "BACKEND_URL": "localhost:3030"
